import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import { PrintActions } from "@/features/pharmacy/components/print-actions";

export default async function PrescriptionReceiptPage({ params }: { params: Promise<{ prescriptionId: string }> }) {
  const resolvedParams = await params;
  
  const prescription = await prisma.prescription.findUnique({
    where: { id: resolvedParams.prescriptionId },
    include: {
      patient: true,
      items: {
        include: { drug: true }
      }
    }
  });

  if (!prescription) return notFound();

  // Basic styling for the receipt print view
  return (
    <div className="bg-white text-black p-8 max-w-2xl mx-auto font-sans" suppressHydrationWarning>
      
      {/* Removed auto-print for pure viewing */}

      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          body { background: white; margin: 0; padding: 0; }
          .no-print { display: none; }
        }
      `}} />

      <div className="border-b-2 border-black pb-4 mb-6 text-center">
        <h1 className="text-3xl font-bold uppercase tracking-wider">Clinic System</h1>
        <p className="text-sm text-gray-600 mt-1">Pharmacy Dispense Receipt</p>
      </div>

      <div className="flex justify-between mb-8 text-sm">
        <div>
          <p><span className="font-semibold">Patient Name:</span> {prescription.patient.firstName} {prescription.patient.lastName}</p>
          <p><span className="font-semibold">Patient ID:</span> {prescription.patient.id}</p>
          <p><span className="font-semibold">Contact:</span> {prescription.patient.contactNumber || 'N/A'}</p>
        </div>
        <div className="text-right">
          <p><span className="font-semibold">Date:</span> {new Date().toLocaleDateString()}</p>
          <p><span className="font-semibold">Prescription ID:</span> {prescription.id}</p>
          <p><span className="font-semibold">Status:</span> {prescription.status.toUpperCase()}</p>
        </div>
      </div>

      <table className="w-full text-left mb-8 border-collapse">
        <thead>
          <tr className="border-b border-black">
            <th className="py-2 font-semibold">Medicine / Drug</th>
            <th className="py-2 font-semibold text-center">Qty</th>
            <th className="py-2 font-semibold">Instructions</th>
          </tr>
        </thead>
        <tbody>
          {prescription.items.map(item => (
            <tr key={item.id} className="border-b border-gray-200">
              <td className="py-3 font-medium">{item.drug.name}</td>
              <td className="py-3 text-center">{item.quantity}</td>
              <td className="py-3 text-sm italic">{item.instructions}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="text-center text-sm text-gray-500 mt-16 pt-4 border-t border-gray-200">
        <p>Please follow the instructions provided by your physician carefully.</p>
        <p className="mt-1">Generated by Clinic Management System</p>
      </div>

      <PrintActions />
    </div>
  );
}
