import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider";
import { prisma } from "@/lib/prisma";
import { TestUserSwitcher } from "@/components/test-user-switcher";

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Gracefully handle db errors during initial build or if db is unreachable
  let isLowPower = true; // Default to true for OptiPlex machines
  try {
    const setting = await prisma.systemSetting.findUnique({ where: { key: "lowPowerMode" } });
    if (setting?.value === "false") isLowPower = false;
  } catch (e) {
    console.error("Could not fetch lowPowerMode setting", e);
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-low-power={isLowPower}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
          <TestUserSwitcher />
        </ThemeProvider>
      </body>
    </html>
  );
}
